[package]
name = "wtmaps"
version = "0.1.0"
authors = ["Yury Delendik <ydelendik@mozilla.com>"]
license = "Apache-2.0 WITH LLVM-exception"
edition = "2018"

[dependencies]
wasmparser = "0.30.0"
vlq = "0.5.1"
serde = "1.0.75"
serde_json = "1.0.39"
docopt = "1.0.1"
